import { SingleBedSharp } from "@mui/icons-material";

const products = [
  {
    _id: "1",
    name: "Car20",
    image: "/images/airpodes.jpg",
    description: "Acool description goes here!",
    brand: "My brand",
    Category: "My category",
    price: 45.56,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Car20",
    image: "/images/airpodes.jpg",
    description: "Acool description goes here!",
    brand: "My brand",
    Category: "My category",
    price: 45.56,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Car20",
    image: "/images/airpodes.jpg",
    description: "Acool description goes here!",
    brand: "My brand",
    Category: "My category",
    price: 45.56,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Car20",
    image: "/images/airpodes.jpg",
    description: "Acool description goes here!",
    brand: "My brand",
    Category: "My category",
    price: 45.56,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Car20",
    image: "/images/airpodes.jpg",
    description: "Acool description goes here!",
    brand: "My brand",
    Category: "My category",
    price: 45.56,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Car20",
    image: "/images/airpodes.jpg",
    description: "Acool description goes here!",
    brand: "My brand",
    Category: "My category",
    price: 45.56,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Car20",
    image: "/images/airpodes.jpg",
    description: "Acool description goes here!",
    brand: "My brand",
    Category: "My category",
    price: 45.56,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
